# Generated by Django 4.2.4 on 2023-08-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monotributo',
            name='vencimiento',
            field=models.CharField(max_length=50),
        ),
    ]
