# Generated by Django 4.2.4 on 2023-08-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoder', '0003_alter_monotributo_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monotributo',
            name='vencimiento',
        ),
    ]
